packages:
  - playground
  - client
  - docs

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - sharp
