name: ci

on:
  push:
    branches:
      - main
      - "**-rc.**"
      - "renovate/**"
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v5

      - run: corepack enable

      - uses: actions/setup-node@v5
        with:
          node-version: lts/-1
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Install Playwright
        run: pnpm playwright-core install

      - run: pnpm dev:prepare

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: "Report Coverage"
        uses: davelosert/vitest-coverage-report-action@v2

      - name: Build
        run: pnpm build
